sonar.projectKey=NubeEra-ImranAli_spring-petclinic
sonar.organization=nubeera-imran-sonar
sonar.host.url=https://sonarcloud.io
sonar.login=2b2592fa4320e0fe2f5a40eb1beb576725f99776

sonar.sources=src
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
